### PR TITLE
ENH: Improvements to News, Teams, and Maintenance Changes

### PR DESCRIPTION
**Pull request by mmcky**
This PR:

- improves the default avatar placeholder
- makes improvements to news page layout
- adjusts spacing around sponsor bar

### CODE REVIEW

**Comment by mmcky** [comment]
@DrDrij I know this is currently in work. I just opened a PR so you can see preview builds.

**Comment by mmcky** [comment]
@DrDrij perhaps we could use GitHub profile pictures for those that haven't submitted a picture for the `team` page

https://github.com/oyamad for Diasuke
https://github.com/mmcky for me

also I think we should remove the `QuantEcon News` title from the News page and perhaps add a more subtle / contextual `News` in the actual site header between the logo and the text. What do you think about that idea?

**Comment by mmcky** [comment]
@DrDrij we should also 

- [ ] reduce the padding around this to be more compact. 

Screenshot 2024-11-26 at 9 04 42 pm

**Comment by mmcky** [comment]
@DrDrij thinking something like this

image

**Comment by mmcky** [comment]
@DrDrij I think we should have `News` or `Activity` in the header rather than in a menu so its a one click access.

Screenshot 2024-12-03 at 10 52 47 am

Looking nice.

**Comment by mmcky** [comment]
@DrDrij if we can wrap up the current change set this week -- that would be great. We can open another PR for next chunk of updates etc.

**Comment by DrDrij** [comment]
@mmcky Currently I had Projects in the primary navigation, and a dropdown of "Code", "Books", "Others".
Maybe these pages should be merged? Or come up with a new layout, they ain't pretty :)

image

**Comment by mmcky** [comment]
> @mmcky Currently I had Projects in the primary navigation, and a dropdown of "Code", "Books", "Others". Maybe these pages should be merged? Or come up with a new layout, they ain't pretty :)
> 
> image

Roger that. Nice idea. I'll add that to my list of actions for the next change set.

**Comment by DrDrij** [comment]
@mmcky The front matter for the badge is free text. Whatever value you add next to the 'badge' key in the news item front-matter, will output the text in the badge.

**Comment by mmcky** [comment]
> @mmcky Currently I had Projects in the primary navigation, and a dropdown of "Code", "Books", "Others". Maybe these pages should be merged? Or come up with a new layout, they ain't pretty :)
> 
> image

Roger that. Nice idea. I'll add that to my list of actions for the next change set.

**Comment by mmcky** [comment]
thanks @DrDrij -- @thomassargent30 had some great feedback and comments on this iteration so I will open an issue for the next round detailing changes.

**Comment by mmcky** [comment]
@jstac I am going to merge this now, but welcome any feedback you have. We can do another round next week.

**Pull request merged**
