### PR TITLE
adding team members

### PR DESCRIPTION
**Pull request by Harveyt47**
Hi @jstac I have added Quentin and Zejin as lead Developers and myself under the QuantEcon Early Career Researchers role, to the QuantEcon team page

### CODE REVIEW

**Comment by jstac** [comment]
Thanks @Harveyt47 .  Could you please ask them if they're willing to provide photos (explain why) and provide one if you're willing.  

It could be great if you could provide me with a screenshot of the web page before I merge, so I know how it's going to look.

**Comment by Harveyt47** [comment]
Hey @jstac hold off on the merge I'll add those photos

**Comment by Harveyt47** [comment]
Hi @jstac Quentin will make a PR when he has a photo. I have added a photo for both Zejin and myself.

**Comment by jstac** [comment]
Thanks @Harveyt47

**Comment by jstac** [comment]
How is this going @Harveyt47 ?  Perhaps we should merge and then ping Quentin again?  Or ping him and then merge?

**Comment by Harveyt47** [comment]
Hey @jstac how do you mean? This has already been merged. I think Quentin was going to make he's own PR once he got his photo.

**Comment by jstac** [comment]
oh yeah, good point `:-)`

**Pull request merged**
