### PR TITLE
Org Site Design Refresh 2023

### PR DESCRIPTION
**Pull request by DrDrij**
This is a large update to the HTML/CSS/JS files used by Jekyll to build the ORG site.

- HTML has been rewritten in Twitter Bootstrap templating format for ease of modifying any layout in the .md files.
- New modern aesthetic has been added, including large homepage hero area.

This update serves the purpose of promoting the QuantEcon brand and highlighting what QuantEcon produces and what services it provides.

### CODE REVIEW

**Comment by mmcky** [comment]
thanks @DrDrij 

@jstac @thomassargent30 I think we are ready to make the org site change permanent. It is currently hosted out of the branch used to make it and we need to merge this and switch to the main branch for the hosting. 

This is a good task to do while @DrDrij is still in town.

**Comment by mmcky** [comment]
@DrDrij I think the next steps are:

- [ ]  update from `main` to incorporate the latest news
- [ ] merge the PR
- [ ] change the branch this points to for hosting back to `main`

**Comment by mmcky** [comment]
@DrDrij would you mind managing this merge process? 

It would be great to get this merged when you are ready

**Review by mmcky — APPROVED** [review]

**Comment by mmcky** [comment]
thanks @DrDrij I love the new site. Love your work ❤️

**Comment by mmcky** [comment]
@DrDrij my Jekyll is not building locally so I can't test my local branch which is just this branch with

```
git checkout master
git pull
git checkout 2022-refresh
git merge master
```

I just wanted to make sure I didn't break anything by updating this branch to the latest master. 

One thing you will need to fix is

`_posts/2023-20-02-rse-workshop.md` needs to be in a proper date format `_posts/2023-02-2-rse-workshop.md` so need to move that file to the new name

**Comment by DrDrij** [comment]
Thank you @mmcky for your overview and guidance. Soft launch successful, moving site to master branch.

**Pull request merged**
