### PR TITLE
Basic site visual updates

### PR DESCRIPTION
**Pull request by DrDrij**
1. "down arrow" should be a bit larger and more visible
2. "About" and "Team" pages can be merged, reducing links on top right.
2. Books need higher visibility

The books are https://dp.quantecon.org/ and https://networks.quantecon.org/

### CODE REVIEW

**Comment by DrDrij** [comment]
- Increased hero arrow size
- Moved team onto about page
- Removed old notebooks page

- Higher visibility for books will go into a new issue.

**Comment by DrDrij** [comment]
@mmcky sorry for my lack of GH etiquette, simple fixes here just need a reviewer please :)

**Comment by mmcky** [comment]
doesn't look like there are preview builds on this repo. But I trust you @DrDrij. Please go ahead and merge when you're ready. :-)

**Review by mmcky — APPROVED** [review]
thanks @DrDrij look forward to seeing the improvements when it is live.

**Pull request merged**
