### PR TITLE
Add support drop down primary menu item

### PR DESCRIPTION
**Pull request by DrDrij**
Merchandise needs to be easier to find. It now lives in the primary navigation at the top of each page under "Support".

@mmcky Just asking for a review please. Not much change, just rearranged the primary menu `<ul>` list and tweaked mobile styles for the menu.

### CODE REVIEW

**Comment by mmcky** [comment]
thanks @DrDrij this looks great

https://deploy-preview-90--sleepy-aryabhata-461b8b.netlify.app

@jstac do we need to ask for Tom's review of this before going live?

**Comment by jstac** [comment]
@mmcky I think let's not bother him --- the change is very minor.
Thanks for putting this together @DrDrij

**Review by mmcky — APPROVED** [review]
@DrDrij this looks great. Thanks.

**Comment by mmcky** [comment]
@DrDrij do you want me to merge this -- or are you happy to manage the deployment?

**Comment by DrDrij** [comment]
> @DrDrij do you want me to merge this -- or are you happy to manage the deployment?

Thanks @mmcky Will merge now :)

**Pull request merged**
