### PR TITLE
MAINT: remove old python lecture page

### PR DESCRIPTION
**Pull request by mmcky**
- [ ] @DrDrij is it OK if we remove this old page.

This will need to be paired with updates to:

- [ ] lecture-python-programming
- [x] lecture-python
- [ ] lecture-python-advanced
- [ ] lecture-python-intro
- [ ] lecture-jax

replacing 

[this page](https://quantecon.org/python-lectures/)

on many `intro.md` pages

and update to 

https://quantecon.org/projects/#filter=lecture

and possible

- [ ] lecture-datascience
- [ ] lecture-julia

### CODE REVIEW

**Comment by mmcky** [comment]
@HengchengZhang would you mind helping to review the `intro.md` pages for the above lecture series.

**Comment by jstac** [comment]
Thanks @mmcky .  Pinging @HengchengZhang and @Jingni0117

**Comment by HengchengZhang** [comment]
Hi @jstac and @mmcky, I think John asked me to delete this line in [#345](https://github.com/QuantEcon/lecture-python.myst/pull/345) in intermediate lectures.

For consistency I suggest we either delete them all to change them to https://quantecon.org/projects/#filter=lecture.

**Comment by mmcky** [comment]
- [ ] rather than delete the page we should setup a permanent redirect to

https://quantecon.org/projects/#filter=lecture

**Comment by mmcky** [comment]
Closing this as stale. Will review the site in our latest `org site review`

**Pull request closed without merging**
