### PR TITLE
Add Intro lectures to Projects page

### PR DESCRIPTION
**Pull request by DrDrij**
This PR adds a link and title square on the Project page (https://quantecon.org/projects/#filter=lecture) for Computational Economics and Finance for Undergraduates (https://intro.quantecon.org/).

@jstac This is parked until you green light.

### CODE REVIEW

**Comment by jstac** [comment]
Thanks @DrDrij .  Title has changed --- see https://intro.quantecon.org/intro.html

**Comment by mmcky** [comment]
@DrDrij I have updated the title in the `md` file

**Comment by mmcky** [comment]
It looks like #107 supersedes this PR

**Comment by HengchengZhang** [comment]
Closed as #107

**Pull request closed without merging**
