### PR TITLE
Add intro

### PR DESCRIPTION
**Pull request by HengchengZhang**
Hi @jstac, this PR removes the current `Lectures` label on the toolbar and adds intro series to `Projects`.

I think we should make the `Lectures` label back after some changes and not a simple link to `Project/lectures`.

### CODE REVIEW

**Comment by jstac** [comment]
Thanks @HengchengZhang .  Does it appear second, after "Python Programming..." and before "Quantitative Economics with Python"

BTW, that last one should be changed to reflect the new title.

**Comment by HengchengZhang** [comment]
Hi @jstac, updated.

**Review by jstac — APPROVED** [review]

**Comment by jstac** [comment]
Thanks @HengchengZhang .  It's hard to review because there's no preview but I'll go ahead and merge.

**Comment by mmcky** [comment]
@jstac there are previews but it just looks a bit different with `Jekyll` 

The bottom of the list is a deploy-preview in the build area

https://deploy-preview-107--sleepy-aryabhata-461b8b.netlify.app

**Comment by jstac** [comment]
Thanks @mmcky

**Pull request merged**
