### PR TITLE
New lectures layout

### PR DESCRIPTION
**Pull request by DrDrij**
- Add "Lectures" section on homepage
- Add new sponsor logo replacing ANU
- Remove DS from projects as now in lectures

### CODE REVIEW

**Comment by mmcky** [comment]
thanks @DrDrij no changes in this need to wait for the lecture split do they (i.e. the python button links to the current python.quantecon.org)?

**Comment by mmcky** [comment]
Do you need me to build this as a test before I merge and deploy?

**Comment by DrDrij** [comment]
@mmcky This is good to go. No need for test deployment. Minor changes to homepage.

**Comment by DrDrij** [comment]
Homepage layout updates:
- Add Schmidt logo to sponsors
- Drop ANU logo from sponsors
- Add new area "Lectures" with py, jl and ds items
- Rename heading "Projects" to "Other Projects"
- Removed ds from projects as it now is under lectures

**Pull request merged**
