### PR TITLE
Content for the Julia Annoucement

### PR DESCRIPTION
**Pull request by jlperla**

### CODE REVIEW

**Comment by jlperla** [comment]
Added acknolwedgement

**Comment by jlperla** [comment]
@mmcky  @DrDrij  This is a starting point for an annoucement on the update of the julia notes.  When we switch the DNS, lets post something like this?  I wasn't sure of the exact format for annoucements, so maybe I missed something somewhere.

Feel free to modify as you wish..  I used the links to the github pages rather than the live julia lectures since the DNS hasn't been switched, but maybe that could be swapped out afterwards.

FYI: @jstac  and @thomassargent30  feel free to modify as you see fit.

**Comment by jstac** [comment]
Looks good to me :+1: 

We'll have to try to get this some attention via tweets, numfocus news announcements, etc.  It will be super useful for the community.

**Comment by mmcky** [comment]
thanks @jlperla and @jstac

**Pull request merged**
